-- AlterTable
ALTER TABLE `companies` MODIFY `atsType` ENUM('GREENHOUSE', 'LEVER', 'ASHBY', 'WORKDAY', 'BAMBOOHR', 'SMARTRECRUITERS', 'TEAMTAILOR', 'PERSONIO', 'GUPY', 'KENOBY', 'SOLIDES', 'LINKEDIN', 'INDEED', 'CATHO', 'APINFO', 'CUSTOM', 'UNKNOWN') NULL;

-- AlterTable
ALTER TABLE `sources` MODIFY `atsType` ENUM('GREENHOUSE', 'LEVER', 'ASHBY', 'WORKDAY', 'BAMBOOHR', 'SMARTRECRUITERS', 'TEAMTAILOR', 'PERSONIO', 'GUPY', 'KENOBY', 'SOLIDES', 'LINKEDIN', 'INDEED', 'CATHO', 'APINFO', 'CUSTOM', 'UNKNOWN') NULL;
